version: '3.8'

services:
  pdfcompare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdfcompare
    restart: unless-stopped
    ports:
      - "5001:5000"
      - "5002:8000"
    security_opt:
      - no-new-privileges:true
    networks:
      - monitoring

networks:
  monitoring:
