version: '3.8'

services:
  pdfapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdfcompare
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - "5000"
      - "5001"
    ports:
      - "5001:5000"
    networks:
      - monitoring

networks:
  monitoring:
